### ISSUE TITLE
Ns_install is requesting confirmation

### ISSUE THREAD

**Issue by glaucogoncalves** [lasseufpa/e2e-slicing-in-a-box#5]
NS-3 Installation doesn't advances because apt is requesting confirmation. Please consider using `-y` parameter.

Moreover, I think that the last `&` in code below must be removed.
`apt install mercurial unzip &>/dev/null &`

**Comment by glaucogoncalves** [comment]
There is an error when installing `cppyy`.

 Now building cppyy-cling
    Creating build directory /tmp/pip-build-_gse8qa3/cppyy-cling/builddir ...
    Running cmake for cppyy-cling: cmake /tmp/pip-build-_gse8qa3/cppyy-cling/src -Wno-dev -DCMAKE_CXX_STANDARD=20 -DLLVM_ENABLE_TERMINFO=0 -DLLVM_ENABLE_ASSERTIONS=0 -Dminimal=ON -Dbuiltin_cling=ON -Druntime_cxxmodules=OFF -Dbuiltin_zlib=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/tmp/pip-build-_gse8qa3/cppyy-cling/builddir/install/cppyy_backend
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    CMake Error at /tmp/pip-build-_gse8qa3/cppyy-cling/builddir/CMakeFiles/CMakeTmp/CMakeLists.txt:14 (add_executable):
      CXX_STANDARD is set to invalid value '20'
    
    
    CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:30 (try_compile):
      Failed to generate test project build system.
    Call Stack (most recent call first):
      CMakeLists.txt:24 (project)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-build-_gse8qa3/cppyy-cling/builddir/CMakeFiles/CMakeOutput.log".
    error: Failed to configure cppyy-cling
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_gse8qa3/cppyy-cling/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4f6jx79_-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-_gse8qa3/cppyy-cling/

**Comment by glaucogoncalves** [comment]
There is other error when executing the last lines with `bake.py`.

>>> Error: missing Python 'distro' package; please install
>>> Error: missing Python 'distro' package; please install
>>> Error: missing Python 'distro' package; please install
>>> Error: missing Python 'distro' package; please install

**Comment by glaucogoncalves** [comment]
Hey @Allbu I check your commit #9028eeb9451e9bdcb90d9bd7acf306759a400018

You added `-y` to lines that install python3 modules. But this options doesn't work.

`python3 -m pip install --user cppyy -y`

Afterall, the error when installing `cppyy` remains.

**Comment by felipebastosb** [comment]
The problem was solved by using gcc compiler instead of bake.py
